ARG UBUNTU_RELEASE=26.04
ARG CHISEL_VERSION=v1.3.0
ARG WRAPPER_VERSION=v1.2.0
ARG TARGETARCH=amd64

FROM ubuntu:$UBUNTU_RELEASE AS builder
ARG TARGETARCH UBUNTU_RELEASE CHISEL_VERSION WRAPPER_VERSION
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates openjdk-21-jdk-headless \
      ca-certificates-java pkgbinarymangler file \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && /usr/sbin/update-ca-certificates \
    && find /etc/ssl/certs/ -name *.pem -exec echo +{} \; > certs \
    && /usr/lib/jvm/java-21-openjdk-amd64/bin/java \
       -jar /usr/share/ca-certificates-java/ca-certificates-java.jar < certs

ADD "https://github.com/canonical/chisel/releases/download/${CHISEL_VERSION}/chisel_${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz" \
    chisel.tar.gz

RUN tar -xvf chisel.tar.gz -C /usr/bin/

ADD "https://github.com/canonical/rocks-toolbox/releases/download/${WRAPPER_VERSION}/rocks-toolbox_${WRAPPER_VERSION}.tar.gz" rocks-toolbox.tar.gz

RUN tar -xvf rocks-toolbox.tar.gz -C /usr/bin/

RUN mkdir -p /staging-rootfs/var/lib/dpkg/ \
    && chisel-wrapper --generate-dpkg-status /staging-rootfs/var/lib/dpkg/status -- \
        --release "ubuntu-${UBUNTU_RELEASE}" --root /staging-rootfs \
        base-files_base \
        base-files_release-info \
        bash_bins \
        ca-certificates_data \
        coreutils_ln-utility \
        zlib1g_libs \
        python3-minimal_bins

# for different base-app: adjust the above list. Have a look at the chisel app list in the canonical repo
# for distroless image: leave out bash and adjust the ENTRYPOINT line (last line)
  
RUN cp -R /etc/passwd /etc/group /etc/ssl /staging-rootfs/etc \
    && install -o ubuntu -g ubuntu -d /staging-rootfs/app \
    && cd /staging-rootfs \
    && chroot . ln -s /usr/lib/jvm/java-21-openjdk-amd64/bin/java /usr/bin/java
   
# second step: start with an empty container and simply copy the staging directory over

FROM scratch

COPY --from=builder /staging-rootfs /

USER ubuntu
WORKDIR /app

ENTRYPOINT ["bash"]
